[project]
name = "mmrphys"
version = "0.1.0"
description = "Multi-Modal Multi-Task Remote Physiological Sensing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.9.1+cpu",
    "torchvision==0.24.1+cpu",
    "scipy>=1.13.0",
    "numpy>=1.26.4",
    "tensorboard>=2.15.2",
    "onnxruntime>=1.23.2",
]

[project.optional-dependencies]
extra = [
    "matplotlib>=3.7.1",
    "opencv-python>=4.9.0.80",
    "PyYAML>=6.0.1",
    "h5py>=3.8.0",
    "yacs>=0.1.8",
    "pandas>=2.0.0",
    "scikit_image>=0.22.0",
    "scikit-learn>=1.7.0",
    "mat73>=0.62",
    "ipykernel>=6.15.0",
    "ipywidgets>=8.1.2",
    "retina-face>=0.0.14",
    "tqdm>=4.65.0",
]

[tool.uv]
package = true
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
